QUESTIONS = [
    # Basics 1-20
    {"id": 1, "question": "What is ServiceNow?", "options": ["DB", "Platform", "OS", "Tool"], "answer": 1},
    {"id": 2, "question": "ServiceNow is based on?", "options": ["Java", "JavaScript", "Python", "C#"], "answer": 1},
    {"id": 3, "question": "Table in ServiceNow stores?", "options": ["Code", "Data", "UI", "Logs"], "answer": 1},
    {"id": 4, "question": "Record means?", "options": ["Row", "Column", "Table", "Script"], "answer": 0},
    {"id": 5, "question": "Field means?", "options": ["Row", "Column", "Table", "Form"], "answer": 1},
    {"id": 6, "question": "Default DB?", "options": ["Oracle", "MySQL", "PostgreSQL", "MongoDB"], "answer": 1},
    {"id": 7, "question": "Instance is?", "options": ["Server copy", "App", "Code", "Table"], "answer": 0},
    {"id": 8, "question": "sys_id is?", "options": ["Name", "Unique ID", "Table", "Role"], "answer": 1},
    {"id": 9, "question": "Form is?", "options": ["Data view", "Script", "Table", "Role"], "answer": 0},
    {"id": 10, "question": "List view shows?", "options": ["One record", "Multiple records", "Script", "Logs"], "answer": 1},
    {"id": 11, "question": "Module is?", "options": ["Script", "Navigation link", "Table", "Form"], "answer": 1},
    {"id": 12, "question": "Application is?", "options": ["Group of modules", "Table", "Field", "Script"], "answer": 0},
    {"id": 13, "question": "Role defines?", "options": ["Data", "Access", "Script", "UI"], "answer": 1},
    {"id": 14, "question": "User table name?", "options": ["sys_user", "user", "u_user", "sys_table"], "answer": 0},
    {"id": 15, "question": "Group table?", "options": ["sys_group", "sys_user_group", "group", "u_group"], "answer": 1},
    {"id": 16, "question": "Client-side scripting uses?", "options": ["Java", "JS", "SQL", "Python"], "answer": 1},
    {"id": 17, "question": "Server-side scripting uses?", "options": ["JS", "SQL", "Java", "XML"], "answer": 0},
    {"id": 18, "question": "UI Policy runs on?", "options": ["Server", "Client", "DB", "API"], "answer": 1},
    {"id": 19, "question": "Business Rule runs on?", "options": ["Client", "Server", "UI", "API"], "answer": 1},
    {"id": 20, "question": "Update Set is used for?", "options": ["Backup", "Migration", "UI", "Logs"], "answer": 1},
    # Scripting 21-40
    {"id": 21, "question": "GlideRecord is used for?", "options": ["UI", "DB ops", "Logs", "API"], "answer": 1},
    {"id": 22, "question": "Insert record method?", "options": ["add()", "insert()", "save()", "create()"], "answer": 1},
    {"id": 23, "question": "Query method?", "options": ["get()", "query()", "fetch()", "read()"], "answer": 1},
    {"id": 24, "question": "Update method?", "options": ["update()", "save()", "write()", "edit()"], "answer": 0},
    {"id": 25, "question": "Delete method?", "options": ["delete()", "remove()", "deleteRecord()", "erase()"], "answer": 2},
    {"id": 26, "question": "Add condition?", "options": ["where()", "addQuery()", "filter()", "cond()"], "answer": 1},
    {"id": 27, "question": "GlideSystem object?", "options": ["gs", "gr", "gl", "sys"], "answer": 0},
    {"id": 28, "question": "Log info?", "options": ["gs.log()", "console.log()", "log()", "info()"], "answer": 0},
    {"id": 29, "question": "Current record object?", "options": ["rec", "current", "obj", "record"], "answer": 1},
    {"id": 30, "question": "Previous record?", "options": ["old", "prev", "previous", "last"], "answer": 2},
    {"id": 31, "question": "Abort action?", "options": ["stop()", "abort()", "setAbortAction()", "end()"], "answer": 2},
    {"id": 32, "question": "Script Include is?", "options": ["Reusable code", "UI", "Table", "API"], "answer": 0},
    {"id": 33, "question": "Client Script types?", "options": ["2", "3", "4", "5"], "answer": 2},
    {"id": 34, "question": "onLoad runs when?", "options": ["Save", "Load", "Delete", "Submit"], "answer": 1},
    {"id": 35, "question": "onSubmit runs when?", "options": ["Load", "Submit", "Delete", "Update"], "answer": 1},
    {"id": 36, "question": "g_form used for?", "options": ["Server", "Client form", "DB", "API"], "answer": 1},
    {"id": 37, "question": "g_user used for?", "options": ["DB", "User info", "UI", "Script"], "answer": 1},
    {"id": 38, "question": "setValue() is?", "options": ["Get", "Set field", "Delete", "Query"], "answer": 1},
    {"id": 39, "question": "getValue() is?", "options": ["Set", "Get field", "Delete", "Query"], "answer": 1},
    {"id": 40, "question": "GlideAjax is used for?", "options": ["Client-server call", "DB", "UI", "Logs"], "answer": 0},
    # UI & Forms 41-60
    {"id": 41, "question": "UI Policy Action controls?", "options": ["DB", "Field behavior", "Script", "Logs"], "answer": 1},
    {"id": 42, "question": "Mandatory field set by?", "options": ["UI Policy", "BR", "Script Include", "API"], "answer": 0},
    {"id": 43, "question": "Read-only field via?", "options": ["UI Policy", "Table", "DB", "API"], "answer": 0},
    {"id": 44, "question": "UI Action appears on?", "options": ["Form/List", "DB", "API", "Script"], "answer": 0},
    {"id": 45, "question": "Button is?", "options": ["UI Action", "BR", "Script", "API"], "answer": 0},
    {"id": 46, "question": "Formatter shows?", "options": ["Extra UI", "DB", "Logs", "Script"], "answer": 0},
    {"id": 47, "question": "Related list shows?", "options": ["Linked records", "Logs", "Scripts", "API"], "answer": 0},
    {"id": 48, "question": "Dictionary defines?", "options": ["Field", "Table", "Script", "API"], "answer": 0},
    {"id": 49, "question": "Choice list is?", "options": ["Dropdown", "Table", "Script", "API"], "answer": 0},
    {"id": 50, "question": "Reference field is?", "options": ["Link to table", "Script", "UI", "API"], "answer": 0},
    {"id": 51, "question": "Form layout changes?", "options": ["Form Designer", "DB", "API", "Logs"], "answer": 0},
    {"id": 52, "question": "List layout controls?", "options": ["Columns", "Script", "DB", "API"], "answer": 0},
    {"id": 53, "question": "UI Script runs on?", "options": ["Client", "Server", "DB", "API"], "answer": 0},
    {"id": 54, "question": "Catalog Item is?", "options": ["Request item", "Script", "DB", "API"], "answer": 0},
    {"id": 55, "question": "Variable is used in?", "options": ["Catalog", "DB", "Script", "API"], "answer": 0},
    {"id": 56, "question": "MRVS means?", "options": ["Multi row var set", "DB", "Script", "API"], "answer": 0},
    {"id": 57, "question": "Portal UI uses?", "options": ["Widgets", "Tables", "DB", "API"], "answer": 0},
    {"id": 58, "question": "Widget uses?", "options": ["HTML/CSS/JS", "Java", "SQL", "Python"], "answer": 0},
    {"id": 59, "question": "Service Portal is?", "options": ["UI layer", "DB", "Script", "API"], "answer": 0},
    {"id": 60, "question": "UI Macro uses?", "options": ["Jelly", "JS", "SQL", "Java"], "answer": 0},
    # Integration & API 61-80
    {"id": 61, "question": "REST API format?", "options": ["XML", "JSON", "Both", "None"], "answer": 2},
    {"id": 62, "question": "SOAP uses?", "options": ["JSON", "XML", "JS", "SQL"], "answer": 1},
    {"id": 63, "question": "Import Set used for?", "options": ["Data import", "UI", "Script", "API"], "answer": 0},
    {"id": 64, "question": "Transform Map maps?", "options": ["Source-target", "UI", "Script", "API"], "answer": 0},
    {"id": 65, "question": "MID Server is?", "options": ["Bridge", "DB", "UI", "Script"], "answer": 0},
    {"id": 66, "question": "IntegrationHub is?", "options": ["Integration tool", "DB", "UI", "Script"], "answer": 0},
    {"id": 67, "question": "Flow Designer is?", "options": ["Automation", "DB", "UI", "Script"], "answer": 0},
    {"id": 68, "question": "Action in flow is?", "options": ["Step", "Table", "Script", "API"], "answer": 0},
    {"id": 69, "question": "Subflow is?", "options": ["Reusable flow", "DB", "UI", "Script"], "answer": 0},
    {"id": 70, "question": "Data source defines?", "options": ["Import source", "UI", "Script", "API"], "answer": 0},
    {"id": 71, "question": "REST Message used for?", "options": ["API call", "UI", "DB", "Script"], "answer": 0},
    {"id": 72, "question": "Scripted REST API is?", "options": ["Custom API", "DB", "UI", "Script"], "answer": 0},
    {"id": 73, "question": "HTTP methods?", "options": ["GET", "POST", "PUT", "All"], "answer": 3},
    {"id": 74, "question": "OAuth is for?", "options": ["Auth", "UI", "DB", "Script"], "answer": 0},
    {"id": 75, "question": "JSON is?", "options": ["Data format", "UI", "DB", "Script"], "answer": 0},
    {"id": 76, "question": "XML is?", "options": ["Data format", "UI", "DB", "Script"], "answer": 0},
    {"id": 77, "question": "Attachment API used for?", "options": ["Files", "UI", "DB", "Script"], "answer": 0},
    {"id": 78, "question": "GlideHTTP used for?", "options": ["HTTP calls", "DB", "UI", "Script"], "answer": 0},
    {"id": 79, "question": "ECC Queue used for?", "options": ["MID comm", "UI", "DB", "Script"], "answer": 0},
    {"id": 80, "question": "Webhook is?", "options": ["Event call", "DB", "UI", "Script"], "answer": 0},
    # Advanced 81-120
    {"id": 81, "question": "ACL controls?", "options": ["Access", "UI", "DB", "Script"], "answer": 0},
    {"id": 82, "question": "Table inheritance is?", "options": ["Extend", "Join", "Map", "Link"], "answer": 0},
    {"id": 83, "question": "Task table is?", "options": ["Parent", "Child", "Script", "API"], "answer": 0},
    {"id": 84, "question": "Incident extends?", "options": ["Task", "User", "Group", "Table"], "answer": 0},
    {"id": 85, "question": "Change request table?", "options": ["change_request", "change", "req", "cr"], "answer": 0},
    {"id": 86, "question": "SLA tracks?", "options": ["Time", "UI", "DB", "Script"], "answer": 0},
    {"id": 87, "question": "Workflow is?", "options": ["Process automation", "DB", "UI", "Script"], "answer": 0},
    {"id": 88, "question": "Flow vs Workflow?", "options": ["New vs old", "Same", "DB", "Script"], "answer": 0},
    {"id": 89, "question": "Scoped app is?", "options": ["Isolated app", "DB", "UI", "Script"], "answer": 0},
    {"id": 90, "question": "Global scope is?", "options": ["Default", "DB", "UI", "Script"], "answer": 0},
    {"id": 91, "question": "Script debugger used for?", "options": ["Debug", "UI", "DB", "API"], "answer": 0},
    {"id": 92, "question": "Logs stored in?", "options": ["syslog", "logs", "sys_table", "debug"], "answer": 0},
    {"id": 93, "question": "Update Set captures?", "options": ["Changes", "DB", "UI", "API"], "answer": 0},
    {"id": 94, "question": "Clone is?", "options": ["Copy instance", "DB", "UI", "Script"], "answer": 0},
    {"id": 95, "question": "Dev instance is?", "options": ["Development", "Prod", "Test", "UI"], "answer": 0},
    {"id": 96, "question": "Prod instance is?", "options": ["Live", "Dev", "Test", "UI"], "answer": 0},
    {"id": 97, "question": "ATF stands for?", "options": ["Automated Test Framework", "API", "UI", "DB"], "answer": 0},
    {"id": 98, "question": "CMDB stores?", "options": ["CI data", "UI", "DB", "Script"], "answer": 0},
    {"id": 99, "question": "CI means?", "options": ["Config Item", "Code", "Script", "UI"], "answer": 0},
    {"id": 100, "question": "Discovery finds?", "options": ["Devices", "UI", "DB", "Script"], "answer": 0},
    {"id": 101, "question": "Event triggers?", "options": ["Notification", "UI", "DB", "Script"], "answer": 0},
    {"id": 102, "question": "Notification sends?", "options": ["Email", "UI", "DB", "Script"], "answer": 0},
    {"id": 103, "question": "Scheduled job runs?", "options": ["Time-based", "UI", "DB", "Script"], "answer": 0},
    {"id": 104, "question": "Fix script used for?", "options": ["One-time run", "UI", "DB", "Script"], "answer": 0},
    {"id": 105, "question": "GlideDateTime used for?", "options": ["Date/time", "UI", "DB", "Script"], "answer": 0},
    {"id": 106, "question": "gs.now() returns?", "options": ["Time", "Date", "Both", "None"], "answer": 2},
    {"id": 107, "question": "Encoded query is?", "options": ["Filter string", "UI", "DB", "Script"], "answer": 0},
    {"id": 108, "question": "Index improves?", "options": ["Performance", "UI", "DB", "Script"], "answer": 0},
    {"id": 109, "question": "Coalesce used in?", "options": ["Import", "UI", "DB", "Script"], "answer": 0},
    {"id": 110, "question": "Data policy runs on?", "options": ["Both", "Client", "Server", "None"], "answer": 0},
    {"id": 111, "question": "Business rule timing?", "options": ["Before", "After", "Async", "All"], "answer": 3},
    {"id": 112, "question": "Async rule runs?", "options": ["Background", "UI", "DB", "Script"], "answer": 0},
    {"id": 113, "question": "Script include type?", "options": ["Class", "Function", "Both", "None"], "answer": 2},
    {"id": 114, "question": "GlideAggregate used for?", "options": ["Count/sum", "UI", "DB", "Script"], "answer": 0},
    {"id": 115, "question": "setDisplay() used for?", "options": ["Show/hide", "UI", "DB", "Script"], "answer": 0},
    {"id": 116, "question": "Order field controls?", "options": ["Execution order", "UI", "DB", "Script"], "answer": 0},
    {"id": 117, "question": "Debug business rule via?", "options": ["Debugger", "UI", "DB", "Script"], "answer": 0},
    {"id": 118, "question": "Table rotation used for?", "options": ["Logs", "UI", "DB", "Script"], "answer": 0},
    {"id": 119, "question": "Performance issue fix?", "options": ["Index", "UI", "DB", "Script"], "answer": 0},
    {"id": 120, "question": "Best practice?", "options": ["Reuse code", "Hardcode", "Skip ACL", "Ignore logs"], "answer": 0},
]
